---
title: Shine on...
timezone: Europe/Rome
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    social-share: true
- scope:
    path: ''
  values:
    layout: page
    show-avatar: true
description: Non ho mai pensato nella vita che per procedere bisogna necessariamente
  andare in linea retta (M. Paolini)
navbar-links:
  <i class="fas fa-user"></i> Chi sono: "/chi-sono"
  <i class="fas fa-hiking"></i> Trekking:
  - Equipaggiamento: "/escursioni/equipaggiamento"
  - Escursioni: "/escursioni"
  - Via del mare: "/escursioni/via-del-mare"
  - Via del sale: "/escursioni/via-del-sale"
  <span style="color:red;"><i class="fas fa-coffee"></i></span> Offrimi un caffè: https://paypal.me/shineon82
avatar: "/img/avatar-icon.png"
round-avatar: true
navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"
author:
  name: Federico Bellinvia
social-network-links:
  rss: true
  email: shineon82@gmail.com
  facebook: shineon82
  instagram: shineon82
  telegram: shìneon82
share-links-active:
  twitter: true
  facebook: true
  linkedin: false
url-pretty: Shineon.it
google_analytics: UA-90050171-1
disqus: shineon-it
staticman:
  repository: 
  branch: master
  endpoint: 
  reCaptcha:
    siteKey: 
    secret: 
utterances:
  repository: 
  issue-term: title
  theme: github-light
  label: blog-comments
excerpt_length: 50
title-separator: "-"
date_format: "%d %B %Y"
markdown: kramdown
highlighter: rouge
permalink: "/:categories/:title/"
paginate: 5
kramdown:
  input: GFM
link-tags: true
exclude:
- CHANGELOG.md
- CNAME
- Dockerfile
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- Vagrantfile
prose:
  rooturl: _posts
  media: img
  ignore:
  - 404.html
  - LICENSE
  - feed.xml
  - _config.yml
  - "/_layouts"
  - "/_includes"
  - "/css"
  - "/img"
  - "/js"
  metadata:
    _posts:
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: Post title
        placeholder: Title
        alterable: true
    - name: subtitle
      field:
        element: textarea
        label: Subtitle
        placeholder: A description of your post.
        alterable: true
    - name: date
      field:
        element: text
        label: Date
        help: Enter date of post.
        placeholder: yyyy-mm-dd
        alterable: true
    - name: image
      field:
        element: text
        label: Image
        help: Add a thumbnail image to your post.
        placeholder: Thumbnail
        alterable: true
    - name: published
      field:
        element: checkbox
        label: Publish
        help: Check to publish post, uncheck to hide.
plugins:
- jekyll-paginate
- jekyll-sitemap
future: false
